version: "3"
services:
  app:
    restart: unless-stopped
    image: django:4.1
    # for producation
    command: gunicorn dj_api_luohu.wsgi:application --workers 3 --bind :8000
    #    for beta
    #    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-api
    hostname: rhapsody
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /d/pycharm/dj_api_luohu:/usr/src/app
      - data_static:/opt/app/assets
    env_file:
      - ./config/.env
    ports:
      - "8000:8000"

  # 静态文件必须使用到nginx
  web:
   depends_on:
    - app
   image: nginx:1.21.0
   ports:
    - 80:80
   environment:
    - TZ=Asia/Shanghai
   volumes:
    # - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx.conf:/etc/nginx/conf.d/resume_nginx.conf
    # - /d/PyCharm/proj_django_resume/proj_django_resume/config/resume_nginx.conf:/etc/nginx/nginx.conf
    - data_nginx_log:/var/log/nginx
#    - data_static:/opt/app/static/
    - ./asset:/opt/app/static/

  volumes:
    data_static:
      # 判断是否外部已有,若无则报错
      # external: true
      name: data_static
    data_nginx_log:


