version: "3"
services:
  app:
    restart: unless-stopped
    image: django:4.1
    # for producation
    command: gunicorn dj_api_luohu.wsgi:application --workers 3 --bind :80
    #    for beta
    #    command: python manage.py runserver 0.0.0.0:80
    container_name: api-django-dev
    hostname: api.esb.alsoapp.com
#    ports:
#      - 8000:8000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /d/pycharm/dj_api_luohu:/opt/app
      - data_static_api:/opt/app/assets
    env_file:
      - ./config/.env

  # 静态文件必须使用到nginx
  web:
   depends_on:
    - app
   image: nginx:1.21.0
   container_name: api-nginx-dev
   ports:
    - 80:80
   environment:
    - TZ=Asia/Shanghai
   volumes:
    - ./config/nginx.conf:/etc/nginx/conf.d/app_nginx.conf
    - data_static_api:/opt/app/static
    - data_nginx_log_api:/var/log/nginx

volumes:
  data_static_api:
  data_nginx_log_api:


