# Generated by Django 4.0.7 on 2022-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTagList',
            fields=[
                ('id', models.BigAutoField(help_text='消息标签记录Id', primary_key=True, serialize=False, verbose_name='消息标签记录Id')),
                ('MSG_ID', models.UUIDField(db_index=True, help_text='消息ID', verbose_name='消息ID')),
                ('mtlTag', models.CharField(help_text='标签', max_length=50, verbose_name='标签')),
                ('mtlText', models.CharField(help_text='标签内容描述', max_length=50, verbose_name='标签内容描述')),
                ('gmt_created', models.DateTimeField(auto_now=True, help_text='记录时间', verbose_name='记录时间')),
            ],
            options={
                'db_table': 'MessageTagList',
            },
        ),
    ]
